// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
// starlight-openapi is wired in Phase 2 once api.corthodex.ai's openapi.yaml
// lands in the codex cache. Until then importing it is harmless but the
// plugin block at the bottom of this file stays commented to avoid a build
// error from the missing schema file.
// import starlightOpenAPI, { openAPISidebarGroups } from 'starlight-openapi';

// https://astro.build/config
export default defineConfig({
	site: 'https://docs.corthodex.ai',
	integrations: [
		starlight({
			title: 'Corthodex API',
			description: 'REST API documentation for the Corthodex education + employment data service',
			logo: { src: './src/assets/logo.svg' },
			customCss: ['./src/styles/custom.css'],
			head: [
				// OpenGraph + Twitter card. og.png is generated by
				// scripts/generate-og.mjs (1200×630, ink palette, logo).
				{
					tag: 'meta',
					attrs: {
						property: 'og:image',
						content: 'https://docs.corthodex.ai/og.png',
					},
				},
				{
					tag: 'meta',
					attrs: { property: 'og:image:width', content: '1200' },
				},
				{
					tag: 'meta',
					attrs: { property: 'og:image:height', content: '630' },
				},
				{
					tag: 'meta',
					attrs: { name: 'twitter:card', content: 'summary_large_image' },
				},
				{
					tag: 'meta',
					attrs: {
						name: 'twitter:image',
						content: 'https://docs.corthodex.ai/og.png',
					},
				},
			],
			social: [],
			sidebar: [
				{
					label: 'Start',
					items: [
						{ label: 'Overview', link: '/' },
						{ label: 'Quickstart', link: '/quickstart/' },
					],
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'API overview', link: '/api/overview/' },
						{ label: 'Authentication', link: '/api/authentication/' },
						{ label: 'Errors', link: '/api/errors/' },
						{ label: 'Pagination', link: '/api/pagination/' },
					],
				},
				{
					label: 'Querying',
					items: [
						{ label: 'Filters', link: '/api/filters/' },
						{ label: 'Cohorts', link: '/api/cohorts/' },
						{ label: 'Metadata', link: '/api/metadata/' },
						{ label: 'Include & merge', link: '/api/include-merge/' },
						{ label: 'Examples', link: '/api/examples/' },
					],
				},
				// ...openAPISidebarGroups,  // re-enable in Phase 2 with the import above
				{
					label: 'Troubleshooting',
					items: [
						{ label: 'Common issues', link: '/troubleshooting/' },
					],
				},
			],
			// plugins: [
			// 	starlightOpenAPI([
			// 		{
			// 			base: 'reference',
			// 			schema: './src/content/docs/api/openapi.yaml',
			// 			label: 'API Reference',
			// 		},
			// 	]),
			// ],
		}),
	],
});
